[deploy]
bucket = 'cfn-artifacts-taskmaster'
region = 'eu-west-2'
stack_name = 'CrudCiCd'

[parameters]
ServiceStack = 'CrudSrvBackendFlask'
ClusterStack = 'CrudCluster'
GitHubBranch = 'production'
GithubRepo = 'TaskMasterErnest/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-cruddur-artifacts-taskmaster"
BuildSpec = 'backend-flask/buildspec.yml'