[deploy]
bucket = 'cfn-artifacts-taskmaster'
region = 'eu-west-2'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:eu-west-2:478429420160:certificate/63d4c16e-e92d-4e4a-a2fe-9c25ddde893e'
NetworkingStack = 'CrdNet'