FROM python:3.10-alpine
	
WORKDIR /backend-flask
	
COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt
	
COPY . .
	
ENV FLASK_ENV=development
	
EXPOSE 4567

RUN chmod +x ./run-flask.sh

ENTRYPOINT [ "./run-flask.sh" ]
