[deploy]
bucket = 'cfn-artifacts-taskmaster'
region = 'eu-west-2'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://thetaskmasterernest.cyou'
EnvBackendUrl = 'https://api.thetaskmasterernest.cyou'
DDBMessageTable = 'CrdDdb-DynamoDBTable-BED4YZSHSOJN'