[deploy]
bucket = 'cfn-artifacts-taskmaster'
region = 'eu-west-2'
stack_name = 'CrudSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://thetaskmasterernest.cyou'
EnvBackendUrl = 'https://api.thetaskmasterernest.cyou'
DDBMessageTable = 'CrudDdb-DynamoDBTable-10FCYBAKN11XB'