FROM node:16.19-alpine AS build

WORKDIR /frontend-react-js
	
COPY package.json .
	
RUN npm install
	
COPY . .
	
RUN npm run build

FROM nginx:stable-alpine
	
COPY --from=build /frontend-react-js/build /usr/share/nginx/html

EXPOSE 8080
