# Specify the base image
FROM node:16.18-alpine as build

# Set the working directory
WORKDIR /app

# Copy the package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the app files
COPY . .

# Build the app
RUN npm run build

# Use the official Nginx image as the base image
FROM nginx:1.19.10-alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the Nginx configuration file from the current directory
COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d
# Copy the built app files from the previous stage to Nginx
COPY --from=build /app/build /usr/share/nginx/html


# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
